[package]
name = "wldash"
version = "0.1.0"
authors = ["Kenny Levinsen <kl@kl.wtf>"]
edition = "2018"

[profile.release]
lto = "fat"

[features]
default = [ "rcalc" ]
ivy = [ "libivy" ]
bc = []
rcalc = [ "rcalc_lib" ]
damage_debug = []

[dependencies]
smithay-client-toolkit = "0.6.4"
byteorder = "1.3"
rusttype = "0.7"
chrono = "0.4"
nix = "0.15"
memmap = "0.7"
os_pipe = "0.8"
wayland-client = { version = "0.23", features = ["dlopen"] }
wayland-protocols = { version = "0.23", features = ["client", "unstable_protocols"] }
libpulse-binding = { version = "2.11"}
dbus = "0.6"
fuzzy-matcher = "0.2"
lazy_static = "1.4"
libivy = { git = "https://github.com/kennylevinsen/libivy.git", optional = true }
rcalc_lib = { version = "0.9", optional = true }
rust-ini = "0.13"
shlex = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
