[package]
name = "wldash"
version = "0.1.0"
authors = ["Kenny Levinsen <kl@kl.wtf>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smithay-client-toolkit = "0.6.3"
byteorder = "1.0"
rusttype = "0.7.7"
chrono = "0.4"
nix = "0.14"
memmap = "0.7"
os_pipe = "0.8.1"